const {
    VITE_GREEN_CHAIN_ID,
    VITE_GREENFIELD_RPC_URL,
    VITE_BSC_RPC_URL,
    VITE_BSC_CHAIN_ID,
    VITE_GRPC_URL,
  
    VITE_BUCKET_BASE_URI,
    VITE_SOCIAL_HUB_CONTRACT,
    VITE_PROFILE_HANDLE_CONTRACT,
    VITE_TOKEN_CONTRACT,
    VITE_REGISTRY_CONTRACT,
    VITE_ACCOUNT_CONTRACT,
    VITE_LEVEL_CONTRACT,
    VITE_EXP_CONTRACT,
  } = import.meta.env;
  
  export const GF_CHAIN_ID = Number(VITE_GREEN_CHAIN_ID);
  export const GF_RPC_URL = VITE_GREENFIELD_RPC_URL as string;
  export const BSC_RPC_URL = VITE_BSC_RPC_URL as string;
  export const BSC_CHAIN_ID = Number(VITE_BSC_CHAIN_ID);
  export const GRPC_URL = VITE_GRPC_URL;
  
  export const BUCKET_BASE_URI = VITE_BUCKET_BASE_URI;
  export const SOCIAL_HUB_CONTRACT = VITE_SOCIAL_HUB_CONTRACT;
  export const PROFILE_HANDLE_CONTRACT = VITE_PROFILE_HANDLE_CONTRACT;
  export const TOKEN_CONTRACT = VITE_TOKEN_CONTRACT;
  export const REGISTRY_CONTRACT = VITE_REGISTRY_CONTRACT;
  export const ACCOUNT_CONTRACT = VITE_ACCOUNT_CONTRACT;
  export const LEVEL_CONTRACT = VITE_LEVEL_CONTRACT;
  export const EXP_CONTRACT = VITE_EXP_CONTRACT